#+TITLE: Web Development With Clojure
#+DATE: 2020-06-01

- tags :: [[file:clojure.org][Clojure]] [[file:book.org][book]]

  Creating an Application from a Template
lein new luminus my-app

By default, Leiningen will use the latest version of the template that has been
published to the Clojars repository.[9] Therefore, the skeleton projects
generated by the template may not be exactly the same as the ones discussed in
the book. In order to ensure that you’re able to follow the book exactly, I
recommend adding the following plugin reference in the

~/.lein/profiles.clj~ file.

This will ensure that the projects are generated using the same version of the
template that was used in the book. ​ 

#+BEGIN_SRC clojure
{:user {:plugins [[luminus/lein-template ​"2.9.10.74"​]]}}
#+END_SRC

#+BEGIN_SRC sh :dir ~/project
lein new luminus guestbook +postgres
#+END_SRC

#+begin_example
Could not find artifact luminus:lein-template:jar: in central (https://repo1.maven.org/maven2/)
Could not find artifact luminus:lein-template:jar: in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
#+end_example

Actually have to delete that change made to profiles.clj file

* start web server
#+BEGIN_SRC sh
lein run
#+END_SRC

on different port:
#+BEGIN_SRC sh
lein run -p 8000
#+END_SRC

Hit error:
#+begin_example
2020-06-01 15:14:42,722 [main] ERROR guestbook.core - Database configuration not found, :database-url environment variable must be set before running
#+end_example

default port: 3000

* migration
#+BEGIN_SRC sh
lein migratus create guestbook
#+END_SRC

lein migrate create guestbook

#+BEGIN_SRC sql
CREATE TABLE test.guestbook (id SERIAL PRIMARY KEY, name VARCHAR(30), message VARCHAR(200), timestamp TIMESTAMP);
#+END_SRC

* connect to postgresql
DATABASE_URL=jdbc:postgresql://localhost/app?user=app_user&password=secret

DATABASE_URL=jdbc:postgresql://192.168.1.231:32990/?user=postgres&password=showgood

Luminus defaults to using SQL template files to interact with the database.

lein repl :connect 7000


user=> (require '[guestbook.db.core :refer :all])
nil
user=> (mount/start #'guestbook.db.core/*db*)
Syntax error reading source at (REPL:1:16).
Index 8203 out of bounds for length 256

user=> (mount.core/start #'guestbook.db.core/*db*)
{:started []}


user=> (get-messages)
Execution error (PSQLException) at org.postgresql.core.v3.QueryExecutorImpl/receiveErrorResponse (QueryExecutorImpl.java:2578).
ERROR: relation "guestbook" does not exist
  Position: 15


ERROR: relation "test.guestbook" does not exist

​;;check the documentation
(doc save-message!)

​;;create a test message​​ 
#+BEGIN_SRC clojure
(save-message! {:name "Bob" :message "Hello, World" :timestamp (java.util.Date.)})
#+END_SRC

user=> (save-message! {:name "Bob" :message "Hello, World" :timestamp (java.util.Date.)})
Execution error (ExceptionInfo) at hugsql.core/validate-parameters! (core.clj:83).
Parameter Mismatch: :name parameter data not found.

turned out the code I copied from book website contains a weird character and I
have to use ~describe-char~ function to get this:
#+begin_example
             position: 18 of 373 (5%), column: 16
            character: ​ (displayed as ​) (codepoint 8203, #o20013, #x200b)
              charset: unicode (Unicode (ISO10646))
code point in charset: 0x200B
               script: symbol
               syntax:   	which means: whitespace
             to input: type "C-x 8 RET 200b" or "C-x 8 RET ZERO WIDTH SPACE"
          buffer code: #xE2 #x80 #x8B
            file code: #xE2 #x80 #x8B (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
    mac-ct:-*-American Typewriter-normal-normal-normal-*-16-*-*-*-p-0-iso10646-1 (#x11C)
#+end_example
